import type { Metadata } from "next";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import FloatingWhatsApp from "@/components/FloatingWhatsApp";
import Breadcrumb from "@/components/Breadcrumb";
import Link from "next/link";

export const dynamic = "force-static";

export const metadata: Metadata = {
  title: "What is Mahadev Book ID? | Online Cricket ID Explained",
  description:
    "Learn exactly what a Mahadev Book ID is, how it differs from a standard online cricket ID, and how to use it safely for sports betting.",
  alternates: {
    canonical: "https://mahadevbooks.today/what-is-mahadev-book-id/",
  },
  openGraph: {
    title: "What is Mahadev Book ID? Complete Guide",
    description:
      "Understand how the Mahadev Book ID works for accessing sports betting and casino platforms securely.",
    url: "https://mahadevbooks.today/what-is-mahadev-book-id/",
    type: "article",
  },
};

const articleJsonLd = {
  "@context": "https://schema.org",
  "@type": "Article",
  headline: "What is Mahadev Book ID? Complete Guide",
  description: "An educational guide explaining what a Mahadev Book ID is and how it functions as a master account for online betting.",
  author: {
    "@type": "Organization",
    name: "Mahadev Book",
    url: "https://mahadevbooks.today",
  },
  publisher: {
    "@type": "Organization",
    name: "Mahadev Book",
    logo: {
      "@type": "ImageObject",
      url: "https://mahadevbooks.today/wp-content/uploads/2025/05/cropped-mahadev-book-logo-120x40.png",
    },
  },
  datePublished: "2026-09-24",
  dateModified: "2026-09-24",
};

export default function WhatIsMahadevBookId() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(articleJsonLd) }}
      />
      <Header />
      <Breadcrumb
        items={[
          { label: "Home", href: "/" },
          { label: "What is Mahadev Book ID" },
        ]}
      />
      <main className="bg-black text-white py-6 px-4 sm:px-6 lg:px-8 space-y-8">
        <section className="max-w-4xl mx-auto border-2 border-gold/40 rounded-2xl p-6 md:p-10 bg-[#0c0c0e] shadow-lg text-center">
          <h1 className="text-2xl md:text-4xl font-extrabold text-gold leading-tight tracking-wide uppercase">
            What is Mahadev Book ID?
          </h1>
          <p className="text-gray-400 text-sm mt-2">The Complete Guide to Understanding Your Betting Account</p>
          <div className="w-24 h-0.5 bg-gold mx-auto mt-4" />
          <p className="text-gray-300 text-base md:text-lg mt-6 leading-relaxed">
            If you are new to the online betting ecosystem in India, you have likely heard the term <strong>Mahadev Book ID</strong>. This informational guide explains exactly what this ID is, how it functions, and how it differs from a generic online cricket ID.
          </p>
        </section>

        <section className="max-w-4xl mx-auto border border-gold/20 rounded-2xl p-6 md:p-10 bg-[#0c0c0e] shadow-lg space-y-6">
          <h2 className="text-xl md:text-2xl font-bold text-gold uppercase tracking-wider">
            Defining the Mahadev Book ID
          </h2>
          <p className="text-gray-300 leading-relaxed">
            A <strong>Mahadev Book ID</strong> is a unique digital identifier assigned to a user upon registration. It acts as a universal master key that grants access to the entire Mahadev Book ecosystem, which includes sports betting (like cricket and football) and online casino games.
          </p>
          <p className="text-gray-300 leading-relaxed">
            Unlike traditional websites where you simply create a username and password, a Mahadev Book ID is typically generated by the platform's support team after verifying your details via WhatsApp. This ID is directly linked to your digital wallet for secure deposits and withdrawals.
          </p>
        </section>

        <section className="max-w-4xl mx-auto border border-gold/20 rounded-2xl p-6 md:p-10 bg-[#0c0c0e] shadow-lg space-y-6">
          <h2 className="text-xl md:text-2xl font-bold text-gold uppercase tracking-wider">
            Mahadev Book ID vs. Online Cricket ID
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="bg-black/40 border border-gray-700 p-5 rounded-xl">
              <h3 className="text-gold font-bold mb-2">Online Cricket ID</h3>
              <p className="text-sm text-gray-300">A generic term used across many different betting platforms. It refers strictly to an account used for betting on cricket matches, often limiting the user to sportsbook markets only.</p>
            </div>
            <div className="bg-black/40 border border-gold/40 p-5 rounded-xl">
              <h3 className="text-gold font-bold mb-2">Mahadev Book ID</h3>
              <p className="text-sm text-gray-300">A brand-specific account that offers a multi-market experience. The same ID allows you to place a bet on the IPL, play live roulette, and enter fantasy tournaments without needing separate accounts.</p>
            </div>
          </div>
        </section>

        <section className="max-w-4xl mx-auto border border-gold/20 rounded-2xl p-6 md:p-10 bg-[#0c0c0e] shadow-lg space-y-4">
          <h2 className="text-xl md:text-2xl font-bold text-gold uppercase tracking-wider">
            How Do You Get a New ID?
          </h2>
          <p className="text-gray-300 leading-relaxed">
            Acquiring a <strong>Mahadev Book new ID</strong> requires contacting the official support channel. For a step-by-step breakdown of this process, please read our complete <Link href="/registration-guide" className="text-gold font-semibold hover:underline">Registration Guide</Link>.
          </p>
          <p className="text-gray-300 leading-relaxed">
            Once generated, you will use this ID to access the platform. Learn how to securely access your account in our <Link href="/login-guide" className="text-gold font-semibold hover:underline">Login Guide</Link>.
          </p>
        </section>

        <section className="max-w-4xl mx-auto text-center mt-8 pb-4">
           <Link
            href="/safety-and-legal"
            className="text-gray-400 hover:text-gold text-sm underline transition-colors"
          >
            Review our Safety & Legal Considerations
          </Link>
        </section>
      </main>
      <Footer />
      <FloatingWhatsApp />
    </>
  );
}
